"""Inventaris kanonis dan immutable untuk cakupan visual Fase 0.

Deklarasi ringkas di bawah adalah sumber denominator. Setiap template menyebut
level aktif, diskriminator cabang parameter, dan nilai cabang yang diizinkan.
Sweep generator di test adalah audit terbatas, bukan pengganti deklarasi ini.
"""

from __future__ import annotations

from types import MappingProxyType
from typing import Any, Mapping

STATUS_VISUAL = frozenset({"wajib_visual", "visual_pendamping", "sengaja_teks"})
INVARIAN_RENDERER_AKTIF = MappingProxyType({
    "korek_api": (
        "jumlah_ruas", "ruas_unik", "topologi_tersambung",
        "pertumbuhan_superset",
    ),
    "titik_segitiga": ("jumlah_titik", "titik_unik"),
})

# Bukti per template: (keluarga representasi, observasi perilaku, konteks varian).
# Kunci eksplisit membuat setiap keputusan dapat diaudit tanpa fallback keluarga.
_BUKTI_TEMPLATE = MappingProxyType({
    "berpapasan": ("gerak", "Jarak awal dan dua kecepatan tertulis langsung; sketsa arah hanya membantu memodelkan waktu temu.", "bawaan"),
    "debit": ("laju", "Volume, waktu, dan debit membentuk satu relasi bagi-kali yang dapat dihitung dari angka tertulis.", "Cabang cari_debit, cari_volume, dan cari_waktu mengubah besaran yang ditanya."),
    "kecepatan_jarak_waktu": ("gerak", "Jarak, waktu, dan kecepatan diberikan numerik; diagram perjalanan tidak menjadi sumber nilai baru.", "Cabang cari_s, cari_t, dan cari_v hanya menukar besaran yang dicari."),
    "kerja_bersama": ("laju", "Waktu kerja masing-masing orang dinyatakan dalam narasi untuk menjumlahkan laju kerja per hari.", "bawaan"),
    "menyusul": ("gerak", "Jarak awal dan selisih dua kecepatan tertulis; sketsa lintasan sekadar memperjelas arah sama.", "bawaan"),
    "perbandingan_berbalik": ("proporsi", "Dua pasangan besaran berlawanan arah disebutkan eksplisit untuk memakai hasil kali tetap.", "bawaan"),
    "perbandingan_senilai": ("proporsi", "Tiga nilai proporsi searah disebutkan eksplisit untuk memperoleh nilai pasangan keempat.", "bawaan"),
    "persen_bertingkat": ("persentase", "Perubahan persen berurutan diterapkan pada nilai antara, sehingga notasi angka adalah objek penalarannya.", "bawaan"),
    "persen_diskon": ("persentase", "Harga awal dan persentase potongan sudah menyatakan seluruh operasi pengurangan secara simbolik.", "bawaan"),
    "persen_untung_rugi": ("persentase", "Harga beli dan harga jual cukup untuk membedakan serta menghitung persentase hasil transaksi.", "Cabang rugi dan untung mengubah arah selisih harga, bukan kebutuhan visual."),
    "satuan_konversi": ("konversi", "Nilai beserta satuan asal dan tujuan menyatakan faktor konversi tanpa perlu tangga bergambar.", "Cabang g_ke_kg, jam_ke_menit, kg_ke_g, km_ke_m, liter_ke_ml, m_ke_km, menit_ke_jam, dan ml_ke_liter tetap berupa konversi numerik."),
    "fpb_dua_bilangan": ("faktor", "Dua bilangan tertulis menjadi input faktorisasi untuk mencari faktor persekutuan terbesar.", "bawaan"),
    "operasi_berkurung": ("operasi", "Tanda kurung pada ekspresi menentukan prioritas hitung dan harus dibaca sebagai notasi simbolik.", "bawaan"),
    "pecahan_kali_bagi": ("pecahan", "Dua pecahan dan operator kali atau bagi tertulis lengkap untuk manipulasi pembilang penyebut.", "bawaan"),
    "pecahan_operasi_campuran": ("pecahan", "Tiga pecahan berbeda penyebut serta operatornya merupakan seluruh informasi untuk menyamakan penyebut.", "bawaan"),
    "pembulatan_taksiran": ("taksiran", "Dua bilangan, satuan pembulatan, dan operator tertulis menguji pembulatan sebelum penaksiran hasil.", "bawaan"),
    "urut_pecahan_desimal_persen": ("representasi_bilangan", "Pecahan, desimal, dan persen perlu disetarakan lalu diurutkan berdasarkan nilai numeriknya.", "bawaan"),
    "urutan_operasi_1": ("operasi", "Ekspresi tanpa kurung menguji prioritas kali-bagi terhadap tambah-kurang melalui simbol tertulis.", "bawaan"),
    "jumlah_sudut_segitiga": ("sudut", "Posisi sudut pada segitiga mengikat nilai yang dijumlahkan hingga seratus delapan puluh derajat.", "Cabang dua_sudut memberi dua ukuran, sedangkan perbandingan memberi rasio sudut pada gambar."),
    "juring": ("lingkaran", "Sektor, jari-jari, dan busurnya perlu terlihat agar batas luas atau keliling tidak tertukar.", "Cabang keliling_juring menyertakan busur dan dua jari-jari; luas_juring menilai daerah sektor."),
    "keliling_luas_datar": ("bangun_datar", "Sisi persegi panjang harus teridentifikasi untuk membaca keliling atau menurunkan luas dari keliling.", "Cabang keliling menghitung batas bangun; balik_luas mencari luas melalui sisi yang diturunkan."),
    "lingkaran_keliling_luas": ("lingkaran", "Jari-jari pada lingkaran harus terbaca agar rumus batas dan daerah memakai ukuran yang benar.", "Cabang keliling membaca batas lingkaran, sedangkan luas membaca daerah lingkaran."),
    "luas_arsiran": ("komposisi_bangun", "Daerah yang diarsir dan dibuang harus dibedakan secara spasial sebelum luas dikurangkan.", "Cabang jalan_pinggir menandai bingkai tepi; persegi_titik_tengah menandai bagian berbasis titik tengah."),
    "luas_kotak_satuan": ("grid", "Banyak kotak pada baris dan kolom harus dibaca dari kisi pengisi persegi panjang.", "bawaan"),
    "luas_segiempat_lain": ("bangun_datar", "Letak tinggi dan diagonal pada trapesium, ketupat, atau layang-layang menentukan ukuran yang dipakai.", "Cabang trapesium memakai sisi sejajar dan tinggi; ketupat_layang memakai dua diagonal; balik_diagonal mencari diagonal hilang."),
    "luas_segitiga_jajargenjang": ("bangun_datar", "Alas dan tinggi tegak harus dibedakan dari sisi miring pada bentuk yang ditampilkan.", "Cabang segitiga memakai setengah alas kali tinggi; jajargenjang memakai alas kali tinggi."),
    "perbandingan_ukuran": ("skala", "Faktor skala dan ukuran awal tertulis cukup; gambar hanya membantu membedakan dimensi pengali.", "Cabang keliling memakai k, luas memakai k kuadrat, dan volume memakai k kubik."),
    "simetri_bangun": ("simetri", "Jumlah sumbu simetri bergantung pada bentuk dan orientasi bangun yang harus diamati.", "Bangun belah_ketupat, persegi, persegi_panjang, dan segitiga_sama_sisi memiliki sumbu berbeda."),
    "sudut_luar_segitiga": ("sudut", "Sudut luar dan dua sudut dalam tak bersisian perlu dikenali melalui posisinya pada gambar.", "bawaan"),
    "sudut_pelurus_berpenyiku": ("sudut", "Sinar dan tanda sudut menunjukkan apakah pasangan membentuk sembilan puluh atau seratus delapan puluh derajat.", "Cabang pelurus, penyiku, balik_pelurus, balik_penyiku, dan tiga_kali mengubah relasi sudut yang divisualkan."),
    "jaring_jaring": ("jaring_ruang", "Susunan enam persegi harus dilihat untuk menilai apakah lipatannya membentuk kubus tanpa tumpang tindih.", "bawaan"),
    "kubus_dicat": ("kubus_satuan", "Letak kubus kecil pada sudut, rusuk, muka, atau bagian dalam menentukan jumlah sisi bercat.", "Cabang nol_sisi, satu_sisi, dua_sisi, tiga_sisi serta nol_sisi_kali, satu_sisi_kali, dua_sisi_kali, tiga_sisi_kali membedakan posisi dan jumlah kubus besar."),
    "luas_permukaan": ("permukaan_ruang", "Muka bangun ruang dan dimensinya perlu dipetakan agar semua bidang permukaan dihitung tepat sekali.", "Cabang kubus_LP, kubus_cari_s, balok_LP, balok_cari_p, tabung_LP, dan tabung_cari_t mencakup hitung maju-balik tiga bangun."),
    "perbandingan_volume": ("skala_ruang", "Volume awal dan faktor panjang tertulis cukup untuk menerapkan faktor kubik; model ruang hanya pendamping.", "Cabang cari_V_baru, cari_k, dan balok_V_baru menukar keluaran atau konteks bangun."),
    "unsur_bangun": ("unsur_ruang", "Rusuk, sisi, dan titik sudut harus dikenali pada bentuk ruang sebelum jumlahnya dihitung.", "Pertanyaan rusuk, sisi, titik, rusuk_kali, sisi_kali, titik_kali diterapkan pada balok, kerucut, kubus, limas_segiempat, prisma_segitiga, dan tabung."),
    "volume_kubus_balok": ("volume_ruang", "Panjang rusuk atau tiga dimensi pada gambar menentukan hasil kali volume dan sisi yang dicari.", "Cabang balok_cari_V, balok_cari_p, kubus_cari_V, dan kubus_cari_s mencakup hitung maju-balik."),
    "volume_prisma_tabung": ("volume_ruang", "Alas, tinggi alas, dan tinggi bangun harus dibedakan pada model prisma atau tabung.", "Cabang prisma_V, prisma_balik, tabung_V, dan tabung_balik menukar bangun serta arah perhitungan."),
    "aturan_kali": ("pencacahan", "Jumlah pilihan pada dua tahap tertulis terpisah untuk dikalikan sebagai pasangan kemungkinan.", "bawaan"),
    "aturan_tambah": ("pencacahan", "Pilihan dari dua kelompok yang saling lepas tertulis untuk dijumlahkan sebagai alternatif.", "bawaan"),
    "inklusi_eksklusi_2": ("himpunan", "Jumlah dua kelompok dan irisannya dinyatakan numerik untuk mengoreksi hitungan ganda.", "bawaan"),
    "jabat_tangan": ("pasangan", "Banyak orang disebutkan langsung untuk membentuk setiap pasangan tak berurutan tepat sekali.", "bawaan"),
    "jalur_petak": ("jalur_grid", "Konektivitas antartitik serta arah gerak pada petak harus terlihat untuk mencacah rute sah.", "bawaan"),
    "kombinasi_pilih": ("kombinasi", "Jumlah objek dan banyak pilihan tertulis untuk menghitung himpunan tanpa memperhatikan urutan.", "bawaan"),
    "permutasi_blok": ("permutasi", "Objek yang wajib berdampingan dinyatakan dalam kalimat dan diperlakukan sebagai satu blok susunan.", "bawaan"),
    "permutasi_urutan": ("permutasi", "Daftar objek dan banyak posisi tertulis untuk menghitung susunan yang membedakan urutan.", "bawaan"),
    "sarang_merpati": ("distribusi", "Jumlah benda dan wadah tertulis untuk menjamin batas minimum isi salah satu wadah.", "bawaan"),
    "susun_bilangan": ("susunan_digit", "Digit tersedia dan panjang bilangan dinyatakan untuk mencacah susunan tanpa pengulangan.", "Cabang dengan_nol melarang nol di depan, sedangkan tanpa_nol tidak memiliki batas itu."),
    "susun_bilangan_syarat": ("susunan_digit", "Digit serta syarat nilai akhir tertulis untuk menyaring susunan bilangan yang diperbolehkan.", "Cabang genap membatasi digit satuan; lebih_dari membatasi nilai keseluruhan bilangan."),
    "benar_salah_pengandaian": ("deduksi", "Pernyataan bersyarat antarobjek tertulis lengkap; tabel atau sketsa hanya membantu eliminasi kemungkinan.", "Cabang bekal menalar barang yang dibawa, sedangkan warna menalar penetapan warna."),
    "dua_besaran_selisih": ("relasi_besaran", "Selisih dan rasio dua besaran tertulis sebagai persamaan untuk menentukan kedua nilainya.", "Cabang besar dan kecil memilih anggota pasangan yang diminta tanpa mengubah relasi."),
    "jumlah_selisih": ("relasi_besaran", "Jumlah total dan selisih dua nilai tertulis sebagai dua persamaan yang dapat diselesaikan.", "Cabang besar dan kecil memilih nilai lebih tinggi atau lebih rendah yang ditanya."),
    "soal_uang": ("relasi_uang", "Total uang dan hubungan antarpemilik disebutkan dalam cerita untuk membentuk persamaan sederhana.", "Cabang uang_besar dan uang_kecil menentukan pemilik dengan jumlah yang diminta."),
    "soal_umur": ("relasi_umur", "Umur kini dan hubungan waktu atau kelipatan tertulis untuk membentuk persamaan usia.", "Cabang kali_umur menanyakan kelipatan, sedangkan n_tahun memindahkan umur sepanjang waktu."),
    "tabel_penalaran": ("urutan_logis", "Petunjuk perbandingan posisi tertulis dapat disusun dalam tabel bantuan tanpa nilai tersembunyi.", "Cabang posisi_dua, posisi_tiga, terendah, dan tertinggi memilih posisi urutan yang ditanya."),
    "jam_menit_detik": ("konversi_waktu", "Besaran waktu dan unit asal-tujuan disebutkan sehingga faktor enam puluh atau tiga ribu enam ratus eksplisit.", "Cabang detik_ke_jam, detik_ke_menit, durasi_ke_detik, durasi_ke_menit, jam_ke_detik, jam_ke_menit, menit_ke_detik, dan menit_ke_jam tetap numerik."),
    "jam_selesai": ("garis_waktu", "Waktu mulai, selesai, atau durasi tertulis; garis waktu hanya mendampingi operasi maju-mundur.", "Cabang cari_durasi, cari_mulai, dan cari_selesai menukar komponen waktu yang belum diketahui."),
    "satuan_kuantitas": ("konversi_kuantitas", "Jumlah lusin, kodi, rim, atau gross dinyatakan dengan nama satuannya untuk dikonversi.", "bawaan"),
    "satuan_luas_volume": ("konversi_dimensi", "Nilai dan unit berpangkat menunjukkan langkah konversi per seratus atau per seribu.", "Cabang luas, tanah, dan volume membedakan faktor dimensi serta keluarga satuan."),
    "satuan_waktu_lama": ("konversi_waktu", "Nilai dan nama periode panjang tertulis langsung untuk dikalikan atau dibagi faktor tahun.", "Cabang abad_ke_dasawarsa, abad_ke_tahun, dasawarsa_ke_tahun, lustrum_ke_tahun, tahun_ke_abad, tahun_ke_dasawarsa, tahun_ke_lustrum, tahun_ke_windu, windu_ke_lustrum, dan windu_ke_tahun tetap simbolik."),
    "skala_peta": ("skala", "Jarak peta, jarak sebenarnya, dan skala numerik membentuk proporsi; gambar peta hanya konteks.", "Cabang cari_peta, cari_sebenarnya, dan cari_skala menentukan komponen proporsi yang hilang."),
    "tangga_satuan_campuran": ("konversi_panjang", "Beberapa nilai panjang dengan unit berbeda tertulis untuk disetarakan sebelum dijumlahkan.", "bawaan"),
    "deret_aritmetika": ("deret", "Suku-suku angka berjarak tetap ditampilkan berurutan sehingga beda dapat ditemukan secara simbolik.", "bawaan"),
    "deret_aritmetika_turun": ("deret", "Suku-suku menurun dengan selisih tetap tertulis berurutan untuk melanjutkan pola pengurangan.", "bawaan"),
    "deret_bertingkat": ("deret", "Selisih antarsuku membentuk pola kedua yang dapat dihitung langsung dari deret angka.", "bawaan"),
    "deret_geometri": ("deret", "Suku-suku angka dengan rasio tetap tertulis berurutan untuk melanjutkan perkalian berulang.", "bawaan"),
    "deret_terbalik_aritmetika": ("deret", "Satu suku hilang di antara angka berselisih tetap dan ditemukan dari tetangganya.", "bawaan"),
    "deret_terbalik_geometri": ("deret", "Satu suku hilang di antara angka berasio tetap dan ditemukan dari tetangganya.", "bawaan"),
    "jumlah_deret": ("jumlah_deret", "Suku awal, beda, dan batas deret tertulis untuk memasangkan atau memakai rumus jumlah.", "bawaan"),
    "jumlah_siklus": ("siklus", "Urutan nilai berulang dan banyak suku tertulis untuk menjumlahkan siklus penuh beserta sisanya.", "bawaan"),
    "korek_api": ("pola_spasial", "Jumlah ruas baru bergantung pada sisi yang berbagi dalam rangkaian batang yang digambar.", "bawaan"),
    "pola_pecahan": ("deret_pecahan", "Pembilang dan penyebut pada urutan pecahan berubah menurut pola numerik yang tertulis.", "bawaan"),
    "siklus_hari": ("siklus_kalender", "Nama hari awal dan jarak hari tertulis untuk memakai sisa pembagian tujuh.", "bawaan"),
    "siklus_huruf": ("siklus_simbol", "Rangkaian huruf berulang ditulis eksplisit sehingga posisi jauh ditentukan melalui panjang siklus.", "bawaan"),
    "siklus_warna": ("siklus_simbol", "Urutan nama warna berulang ditulis eksplisit sehingga posisi berikutnya tidak memerlukan gambar berwarna.", "bawaan"),
    "sisa_bagi_siklus": ("siklus", "Panjang siklus dan nomor posisi tertulis untuk memetakan sisa pembagian ke anggota urutan.", "bawaan"),
    "suku_ke_n": ("deret", "Suku awal, beda, dan indeks tujuan tertulis untuk menghitung suku umum aritmetika.", "bawaan"),
    "titik_segitiga": ("pola_spasial", "Baris-baris titik membentuk segitiga dan jumlahnya harus dibaca sebagai pertumbuhan susunan dua dimensi.", "bawaan"),
    "diagram_batang_garis": ("diagram_data", "Tinggi batang atau posisi titik terhadap sumbu menjadi sumber nilai tiap kategori.", "Cabang baca mengambil satu nilai, jumlah menjumlah kategori, dan selisih membandingkan dua kategori."),
    "diagram_lingkaran": ("diagram_data", "Besar sektor terhadap satu lingkaran utuh menunjukkan proporsi kategori yang harus dibaca.", "Cabang cari_nilai mengubah sudut menjadi banyak data; cari_sudut mengubah banyak data menjadi sudut."),
    "jangkauan_data": ("daftar_data", "Daftar bilangan tertulis memungkinkan nilai minimum dan maksimum ditemukan lalu dikurangkan.", "Cabang jangkauan, terbesar, dan terkecil memilih hasil ringkasan dari daftar yang sama."),
    "median_modus": ("daftar_data", "Daftar angka perlu diurutkan atau dihitung frekuensinya tanpa representasi grafis tambahan.", "Cabang median memilih nilai tengah, sedangkan modus memilih nilai yang paling sering muncul."),
    "piktogram": ("diagram_data", "Jumlah ikon dan nilai setiap ikon harus terlihat untuk memperoleh kuantitas kategori.", "Cabang baca mengambil satu kategori, selisih membandingkan kategori, dan total menjumlah semuanya."),
    "rata_rata": ("daftar_data", "Nilai-nilai tertulis dijumlahkan dan dibagi banyak data, atau dibalik untuk mencari data hilang.", "Cabang cari_rata menghitung mean; cari_data_ke_n memulihkan satu nilai yang belum diketahui."),
    "rata_rata_gabungan": ("ringkasan_data", "Banyak anggota dan rata-rata tiap kelompok tertulis untuk menghitung total tertimbang gabungan.", "bawaan"),
    "tabel_turus": ("tabel_frekuensi", "Kelompok lima garis turus harus dibaca secara visual untuk memperoleh frekuensi tiap kategori.", "Cabang baca mengambil frekuensi, jumlah menjumlah frekuensi, dan terbanyak memilih kategori maksimum."),
    "angka_satuan_pangkat": ("pola_digit", "Basis dan pangkat tertulis untuk menelusuri siklus digit satuan secara aritmetis.", "bawaan"),
    "fpb_kpk_hubungan": ("faktor_kelipatan", "FPB, KPK, dan salah satu bilangan tertulis dalam identitas hasil kali dua bilangan.", "bawaan"),
    "gauss_deret": ("jumlah_bilangan", "Batas awal dan akhir bilangan berurutan tertulis untuk dipasangkan dalam penjumlahan Gauss.", "bawaan"),
    "keterbagian": ("aturan_digit", "Digit-digit bilangan tertulis menjadi bahan penerapan aturan habis bagi tertentu.", "bawaan"),
    "kpk_dua_bilangan": ("faktor_kelipatan", "Dua bilangan tertulis menjadi input faktorisasi untuk mencari kelipatan persekutuan terkecil.", "bawaan"),
    "paritas": ("ganjil_genap", "Operasi pada bilangan ganjil atau genap tertulis untuk menalar paritas hasilnya.", "bawaan"),
    "prima_faktorisasi": ("faktor_prima", "Satu bilangan tertulis diuraikan menjadi perkalian faktor prima tanpa informasi spasial.", "bawaan"),
    "sisa_pembagian": ("modulo", "Bilangan yang dibagi dan pembagi tertulis langsung untuk menentukan sisa aritmetika.", "bawaan"),
})

# topik, template, status, level, diskriminator, nilai varian, override per level
_ROWS = [('aritmatika-lanjut', 'berpapasan', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('aritmatika-lanjut',
  'debit',
  'visual_pendamping',
  ('P5', 'P6'),
  ('varian',),
  ('varian=cari_debit', 'varian=cari_volume', 'varian=cari_waktu'),
  {}),
 ('aritmatika-lanjut',
  'kecepatan_jarak_waktu',
  'visual_pendamping',
  ('P5', 'P6'),
  ('varian',),
  ('varian=cari_s', 'varian=cari_t', 'varian=cari_v'),
  {}),
 ('aritmatika-lanjut', 'kerja_bersama', 'visual_pendamping', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'menyusul', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'perbandingan_berbalik', 'visual_pendamping', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'perbandingan_senilai', 'visual_pendamping', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'persen_bertingkat', 'sengaja_teks', ('P6',), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'persen_diskon', 'sengaja_teks', ('P5',), (), ('bawaan',), {}),
 ('aritmatika-lanjut', 'persen_untung_rugi', 'sengaja_teks', ('P6',), ('jenis',), ('jenis=rugi', 'jenis=untung'), {}),
 ('aritmatika-lanjut',
  'satuan_konversi',
  'visual_pendamping',
  ('P5', 'P6'),
  ('varian',),
  ('varian=g_ke_kg',
   'varian=jam_ke_menit',
   'varian=kg_ke_g',
   'varian=km_ke_m',
   'varian=liter_ke_ml',
   'varian=m_ke_km',
   'varian=menit_ke_jam',
   'varian=ml_ke_liter'),
  {}),
 ('aritmetika-dasar', 'fpb_dua_bilangan', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'operasi_berkurung', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'pecahan_kali_bagi', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'pecahan_operasi_campuran', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'pembulatan_taksiran', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'urut_pecahan_desimal_persen', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('aritmetika-dasar', 'urutan_operasi_1', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('geometri-datar',
  'jumlah_sudut_segitiga',
  'wajib_visual',
  ('P4', 'P5'),
  ('varian',),
  ('varian=dua_sudut', 'varian=perbandingan'),
  {}),
 ('geometri-datar',
  'juring',
  'wajib_visual',
  ('P6',),
  ('varian',),
  ('varian=keliling_juring', 'varian=luas_juring'),
  {}),
 ('geometri-datar',
  'keliling_luas_datar',
  'wajib_visual',
  ('P3', 'P4', 'P5', 'P6'),
  ('varian',),
  ('varian=balik_luas', 'varian=keliling'),
  {'P3': ('varian=keliling',)}),
 ('geometri-datar',
  'lingkaran_keliling_luas',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=keliling', 'varian=luas'),
  {}),
 ('geometri-datar',
  'luas_arsiran',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=jalan_pinggir', 'varian=persegi_titik_tengah'),
  {}),
 ('geometri-datar', 'luas_kotak_satuan', 'wajib_visual', ('P3',), (), ('bawaan',), {}),
 ('geometri-datar',
  'luas_segiempat_lain',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=balik_diagonal', 'varian=ketupat_layang', 'varian=trapesium'),
  {}),
 ('geometri-datar',
  'luas_segitiga_jajargenjang',
  'wajib_visual',
  ('P4', 'P5', 'P6'),
  ('varian',),
  ('varian=jajargenjang', 'varian=segitiga'),
  {}),
 ('geometri-datar',
  'perbandingan_ukuran',
  'visual_pendamping',
  ('P6',),
  ('varian',),
  ('varian=keliling', 'varian=luas', 'varian=volume'),
  {}),
 ('geometri-datar',
  'simetri_bangun',
  'wajib_visual',
  ('P3',),
  ('bangun',),
  ('bangun=belah_ketupat', 'bangun=persegi', 'bangun=persegi_panjang', 'bangun=segitiga_sama_sisi'),
  {}),
 ('geometri-datar', 'sudut_luar_segitiga', 'wajib_visual', ('P5', 'P6'), (), ('bawaan',), {}),
 ('geometri-datar',
  'sudut_pelurus_berpenyiku',
  'wajib_visual',
  ('P4', 'P5'),
  ('varian',),
  ('varian=balik_pelurus', 'varian=balik_penyiku', 'varian=pelurus', 'varian=penyiku', 'varian=tiga_kali'),
  {}),
 ('geometri-ruang', 'jaring_jaring', 'wajib_visual', ('P6',), (), ('bawaan',), {}),
 ('geometri-ruang',
  'kubus_dicat',
  'wajib_visual',
  ('P6',),
  ('tanya',),
  ('tanya=dua_sisi',
   'tanya=dua_sisi_kali',
   'tanya=nol_sisi',
   'tanya=nol_sisi_kali',
   'tanya=satu_sisi',
   'tanya=satu_sisi_kali',
   'tanya=tiga_sisi',
   'tanya=tiga_sisi_kali'),
  {}),
 ('geometri-ruang',
  'luas_permukaan',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=balok_LP',
   'varian=balok_cari_p',
   'varian=kubus_LP',
   'varian=kubus_cari_s',
   'varian=tabung_LP',
   'varian=tabung_cari_t'),
  {}),
 ('geometri-ruang',
  'perbandingan_volume',
  'visual_pendamping',
  ('P6',),
  ('varian',),
  ('varian=balok_V_baru', 'varian=cari_V_baru', 'varian=cari_k'),
  {}),
 ('geometri-ruang',
  'unsur_bangun',
  'wajib_visual',
  ('P5', 'P6'),
  ('tanya', 'bangun'),
  ('tanya=rusuk_kali|bangun=balok',
   'tanya=rusuk_kali|bangun=kerucut',
   'tanya=rusuk_kali|bangun=kubus',
   'tanya=rusuk_kali|bangun=limas_segiempat',
   'tanya=rusuk_kali|bangun=prisma_segitiga',
   'tanya=rusuk_kali|bangun=tabung',
   'tanya=rusuk|bangun=balok',
   'tanya=rusuk|bangun=kerucut',
   'tanya=rusuk|bangun=kubus',
   'tanya=rusuk|bangun=limas_segiempat',
   'tanya=rusuk|bangun=prisma_segitiga',
   'tanya=rusuk|bangun=tabung',
   'tanya=sisi_kali|bangun=balok',
   'tanya=sisi_kali|bangun=kerucut',
   'tanya=sisi_kali|bangun=kubus',
   'tanya=sisi_kali|bangun=limas_segiempat',
   'tanya=sisi_kali|bangun=prisma_segitiga',
   'tanya=sisi_kali|bangun=tabung',
   'tanya=sisi|bangun=balok',
   'tanya=sisi|bangun=kerucut',
   'tanya=sisi|bangun=kubus',
   'tanya=sisi|bangun=limas_segiempat',
   'tanya=sisi|bangun=prisma_segitiga',
   'tanya=sisi|bangun=tabung',
   'tanya=titik_kali|bangun=balok',
   'tanya=titik_kali|bangun=kerucut',
   'tanya=titik_kali|bangun=kubus',
   'tanya=titik_kali|bangun=limas_segiempat',
   'tanya=titik_kali|bangun=prisma_segitiga',
   'tanya=titik_kali|bangun=tabung',
   'tanya=titik|bangun=balok',
   'tanya=titik|bangun=kerucut',
   'tanya=titik|bangun=kubus',
   'tanya=titik|bangun=limas_segiempat',
   'tanya=titik|bangun=prisma_segitiga',
   'tanya=titik|bangun=tabung'),
  {}),
 ('geometri-ruang',
  'volume_kubus_balok',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=balok_cari_V', 'varian=balok_cari_p', 'varian=kubus_cari_V', 'varian=kubus_cari_s'),
  {}),
 ('geometri-ruang',
  'volume_prisma_tabung',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=prisma_V', 'varian=prisma_balik', 'varian=tabung_V', 'varian=tabung_balik'),
  {}),
 ('kombinatorik', 'aturan_kali', 'visual_pendamping', ('P5',), (), ('bawaan',), {}),
 ('kombinatorik', 'aturan_tambah', 'visual_pendamping', ('P5',), (), ('bawaan',), {}),
 ('kombinatorik', 'inklusi_eksklusi_2', 'visual_pendamping', ('P5', 'P6'), (), ('bawaan',), {}),
 ('kombinatorik', 'jabat_tangan', 'visual_pendamping', ('P5',), (), ('bawaan',), {}),
 ('kombinatorik', 'jalur_petak', 'wajib_visual', ('P6',), (), ('bawaan',), {}),
 ('kombinatorik', 'kombinasi_pilih', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('kombinatorik', 'permutasi_blok', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('kombinatorik', 'permutasi_urutan', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('kombinatorik', 'sarang_merpati', 'visual_pendamping', ('P6',), (), ('bawaan',), {}),
 ('kombinatorik',
  'susun_bilangan',
  'visual_pendamping',
  ('P5',),
  ('varian',),
  ('varian=dengan_nol', 'varian=tanpa_nol'),
  {}),
 ('kombinatorik',
  'susun_bilangan_syarat',
  'visual_pendamping',
  ('P5', 'P6'),
  ('varian',),
  ('varian=genap', 'varian=lebih_dari'),
  {}),
 ('logika',
  'benar_salah_pengandaian',
  'visual_pendamping',
  ('P3', 'P5', 'P6'),
  ('varian',),
  ('varian=bekal', 'varian=warna'),
  {}),
 ('logika', 'dua_besaran_selisih', 'visual_pendamping', ('P6',), ('tanya',), ('tanya=besar', 'tanya=kecil'), {}),
 ('logika', 'jumlah_selisih', 'visual_pendamping', ('P5', 'P6'), ('tanya',), ('tanya=besar', 'tanya=kecil'), {}),
 ('logika',
  'soal_uang',
  'visual_pendamping',
  ('P3', 'P5', 'P6'),
  ('tanya',),
  ('tanya=uang_besar', 'tanya=uang_kecil'),
  {}),
 ('logika', 'soal_umur', 'visual_pendamping', ('P3', 'P6'), ('tanya',), ('tanya=kali_umur', 'tanya=n_tahun'), {}),
 ('logika',
  'tabel_penalaran',
  'visual_pendamping',
  ('P3', 'P5', 'P6'),
  ('tanya',),
  ('tanya=posisi_dua', 'tanya=posisi_tiga', 'tanya=terendah', 'tanya=tertinggi'),
  {'P3': ('tanya=posisi_dua', 'tanya=terendah', 'tanya=tertinggi')}),
 ('pengukuran',
  'jam_menit_detik',
  'visual_pendamping',
  ('P4', 'P5', 'P6'),
  ('varian',),
  ('varian=detik_ke_jam',
   'varian=detik_ke_menit',
   'varian=durasi_ke_detik',
   'varian=durasi_ke_menit',
   'varian=jam_ke_detik',
   'varian=jam_ke_menit',
   'varian=menit_ke_detik',
   'varian=menit_ke_jam'),
  {}),
 ('pengukuran',
  'jam_selesai',
  'visual_pendamping',
  ('P4', 'P5', 'P6'),
  ('varian',),
  ('varian=cari_durasi', 'varian=cari_mulai', 'varian=cari_selesai'),
  {}),
 ('pengukuran', 'satuan_kuantitas', 'visual_pendamping', ('P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pengukuran',
  'satuan_luas_volume',
  'visual_pendamping',
  ('P5', 'P6'),
  ('jenis',),
  ('jenis=luas', 'jenis=tanah', 'jenis=volume'),
  {}),
 ('pengukuran',
  'satuan_waktu_lama',
  'visual_pendamping',
  ('P4', 'P5', 'P6'),
  ('varian',),
  ('varian=abad_ke_dasawarsa',
   'varian=abad_ke_tahun',
   'varian=dasawarsa_ke_tahun',
   'varian=lustrum_ke_tahun',
   'varian=tahun_ke_abad',
   'varian=tahun_ke_dasawarsa',
   'varian=tahun_ke_lustrum',
   'varian=tahun_ke_windu',
   'varian=windu_ke_lustrum',
   'varian=windu_ke_tahun'),
  {}),
 ('pengukuran',
  'skala_peta',
  'visual_pendamping',
  ('P5', 'P6'),
  ('varian',),
  ('varian=cari_peta', 'varian=cari_sebenarnya', 'varian=cari_skala'),
  {}),
 ('pengukuran', 'tangga_satuan_campuran', 'visual_pendamping', ('P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_aritmetika', 'sengaja_teks', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_aritmetika_turun', 'sengaja_teks', ('P3', 'P4'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_bertingkat', 'sengaja_teks', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_geometri', 'sengaja_teks', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_terbalik_aritmetika', 'sengaja_teks', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'deret_terbalik_geometri', 'sengaja_teks', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'jumlah_deret', 'sengaja_teks', ('P6',), (), ('bawaan',), {}),
 ('pola-bilangan', 'jumlah_siklus', 'sengaja_teks', ('P3', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'korek_api', 'wajib_visual', ('P3', 'P4', 'P5'), (), ('bawaan',), {}),
 ('pola-bilangan', 'pola_pecahan', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'siklus_hari', 'sengaja_teks', ('P3', 'P4', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'siklus_huruf', 'sengaja_teks', ('P3', 'P4', 'P5'), (), ('bawaan',), {}),
 ('pola-bilangan', 'siklus_warna', 'sengaja_teks', ('P3',), (), ('bawaan',), {}),
 ('pola-bilangan', 'sisa_bagi_siklus', 'sengaja_teks', ('P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'suku_ke_n', 'sengaja_teks', ('P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('pola-bilangan', 'titik_segitiga', 'wajib_visual', ('P3', 'P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('statistika',
  'diagram_batang_garis',
  'wajib_visual',
  ('P3', 'P4', 'P5', 'P6'),
  ('varian',),
  ('varian=baca', 'varian=jumlah', 'varian=selisih'),
  {}),
 ('statistika',
  'diagram_lingkaran',
  'wajib_visual',
  ('P5', 'P6'),
  ('varian',),
  ('varian=cari_nilai', 'varian=cari_sudut'),
  {}),
 ('statistika',
  'jangkauan_data',
  'sengaja_teks',
  ('P3', 'P4'),
  ('varian',),
  ('varian=jangkauan', 'varian=terbesar', 'varian=terkecil'),
  {}),
 ('statistika',
  'median_modus',
  'sengaja_teks',
  ('P3', 'P4', 'P5', 'P6'),
  ('varian',),
  ('varian=median', 'varian=modus'),
  {'P3': ('varian=modus',)}),
 ('statistika',
  'piktogram',
  'wajib_visual',
  ('P3', 'P4'),
  ('varian',),
  ('varian=baca', 'varian=selisih', 'varian=total'),
  {}),
 ('statistika',
  'rata_rata',
  'sengaja_teks',
  ('P4', 'P5', 'P6'),
  ('varian',),
  ('varian=cari_data_ke_n', 'varian=cari_rata'),
  {}),
 ('statistika', 'rata_rata_gabungan', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('statistika',
  'tabel_turus',
  'wajib_visual',
  ('P3', 'P4'),
  ('varian',),
  ('varian=baca', 'varian=jumlah', 'varian=terbanyak'),
  {}),
 ('teori-bilangan', 'angka_satuan_pangkat', 'sengaja_teks', ('P6',), (), ('bawaan',), {}),
 ('teori-bilangan', 'fpb_kpk_hubungan', 'sengaja_teks', ('P6',), (), ('bawaan',), {}),
 ('teori-bilangan', 'gauss_deret', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('teori-bilangan', 'keterbagian', 'sengaja_teks', ('P4', 'P5', 'P6'), (), ('bawaan',), {}),
 ('teori-bilangan', 'kpk_dua_bilangan', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('teori-bilangan', 'paritas', 'sengaja_teks', ('P4', 'P5'), (), ('bawaan',), {}),
 ('teori-bilangan', 'prima_faktorisasi', 'sengaja_teks', ('P5', 'P6'), (), ('bawaan',), {}),
 ('teori-bilangan', 'sisa_pembagian', 'sengaja_teks', ('P4', 'P5', 'P6'), (), ('bawaan',), {})]


def _bekukan(nilai: Any) -> Any:
    """Bekukan mapping/list bersarang agar API tidak membocorkan state mutable."""
    if isinstance(nilai, dict):
        return MappingProxyType({k: _bekukan(v) for k, v in nilai.items()})
    if isinstance(nilai, (list, tuple)):
        return tuple(_bekukan(v) for v in nilai)
    return nilai


def _alasan(template_id: str, bukti: Mapping[str, str]) -> str:
    return f"{template_id}: {bukti['observasi']}"


def _bangun_item(row: tuple[Any, ...]) -> Mapping[str, Any]:
    topik_id, template_id, status, levels, diskriminator, nilai, overrides = row
    if status not in STATUS_VISUAL:
        raise ValueError(f"status visual tidak dikenal: {status!r}")
    try:
        keluarga, observasi, konteks_varian = _BUKTI_TEMPLATE[template_id]
    except KeyError as galat:
        raise ValueError(
            f"bukti klasifikasi belum dideklarasikan: {template_id}"
        ) from galat
    bukti = {
        "keluarga": keluarga,
        "observasi": observasi,
        "konteks_varian": konteks_varian,
        "keputusan": status,
    }
    per_level = {
        level: tuple(overrides.get(level, nilai))
        for level in levels
    }
    item = {
        "topik_id": topik_id,
        "template_id": template_id,
        "status": status,
        "bukti_klasifikasi": bukti,
        "alasan": _alasan(template_id, bukti),
        "deklarasi_varian": {
            "diskriminator": tuple(diskriminator),
            "nilai": tuple(nilai),
        },
        "varian_generator": per_level,
    }
    return _bekukan(item)


_INVENTARIS = tuple(_bangun_item(row) for row in _ROWS)
_BY_TEMPLATE = MappingProxyType({item["template_id"]: item for item in _INVENTARIS})


def identitas_varian(template_id: str, parameter: Mapping[str, Any]) -> str:
    """Identifikasi cabang generator dan tolak varian di luar deklarasi template."""
    try:
        deklarasi = _BY_TEMPLATE[template_id]["deklarasi_varian"]
    except KeyError as galat:
        raise ValueError(f"template {template_id!r} tidak ada di inventaris") from galat
    diskriminator = deklarasi["diskriminator"]
    identitas = "|".join(
        f"{nama}={parameter[nama]}" for nama in diskriminator
    ) if diskriminator else "bawaan"
    if identitas not in deklarasi["nilai"]:
        raise ValueError(
            f"varian {identitas!r} untuk {template_id!r} tidak dideklarasikan"
        )
    return identitas


def inventaris_template() -> tuple[Mapping[str, Any], ...]:
    """Kembalikan view inventaris yang immutable hingga struktur terdalam."""
    return _INVENTARIS


DENOMINATOR_KANONIS = tuple(
    _bekukan({
        "topik_id": item["topik_id"],
        "level": level,
        "template_id": item["template_id"],
        "varian": varian,
        "status": item["status"],
        "bukti_klasifikasi": item["bukti_klasifikasi"],
        "alasan": item["alasan"],
    })
    for item in _INVENTARIS
    for level, varian_level in item["varian_generator"].items()
    for varian in varian_level
)
